Feature/feature slave set
IOT-DSA/dslink-java-modbus pull request #13
Opened 2016-12-17 01:17 UTC by hhou2011

@Pacane

2016-12-19 15:40 UTC, Pacane requested changes

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +		case TCP: {
don't need the brackets in the `case`. Although I don't know what's the standard.

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +
rm empty line

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +
rm empty line

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +
rm empty line

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +	// Handler<ActionResult> getAddDeviceActionHandler() {
remove this if not used anymore.

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +			long interval = (long) (event.getParameter("polling interval", ValueType.NUMBER).getNumber().doubleValue()
any reason why this is a `double` ?

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +		this.statnode = node.createChild("STATUS").setValueType(ValueType.STRING)
I think the name shouldn't be capitalized. (Or do you want to reference a constant?)

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +
rm empty line

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +
rm empty line

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +				statnode.setValue(new Value("Ready"));
Should that be a constant or an Enum value? Looks like it's referenced a few times in clear text like this.

2016-12-19 15:40 UTC, Pacane commented on src/main/java/modbus/SlaveFolder.java
> +		return null;
Should add a TODO or something.

2016-12-19 19:43 UTC, hhou2011 commented on src/main/java/modbus/SlaveFolder.java
> +		return null;
I will have a refactoring on this design.

2016-12-20 16:43 UTC, Pacane requested changes

2016-12-20 16:43 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +    static final String ATTR_STATUS_NODE = "Status";
formatting.

2016-12-24 02:30 UTC, Pacane requested changes

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +		getMasterAttributes();
I'm not sure what that does, but if it has some side effect, maybe it shouldn't be named getSomething

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +			master = new ModbusFactory().createUdpMaster(params);
The factory should be injected, but since we dont do DI, you could just instantiate it once in the constructor

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +			readMasterParameters(event);
Same comment here, you should name it clearer if there's a side effect. Here I dont really know what it does, nor do I see what object it acts upon.

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +			long interval = (long) (event.getParameter("polling interval", ValueType.NUMBER).getNumber().intValue()
Can be named intervalInMs

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/IpConnection.java
> +			boolean contig = event.getParameter("contiguous batch requests only", ValueType.BOOL).getBool();
Param names could be extractes

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +		node.setAttribute("restoreType", new Value("conn"));
Use extracted

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +			node.removeChild("stop");
Extract stop

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +		if (node.getChildren() == null)
Was there a hasChildren Method available? I'm not sure

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +		Node anode = node.getChild("remove");
Extract

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +			if (retryDelay < 60)
Extract both values

2016-12-24 02:30 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +	public void getMasterAttributes() {
Could be renamed loadMasterAttributes or something like that

2016-12-24 14:31 UTC, Pacane commented
There are a bunch of fields in there that could easily be extracted to constant, and re-used (like the Parameter names, being reused in the "handle" method)

2016-12-24 14:32 UTC, Pacane requested changes

2016-12-24 14:32 UTC, Pacane commented on src/main/java/modbus/SlaveFolder.java
> +		return null;
add todo here?

2016-12-24 14:32 UTC, Pacane commented on src/main/java/modbus/SlaveFolder.java
> +		if (root.getMaster() == null) {
side effect in a get/read method.

2016-12-24 14:32 UTC, Pacane commented on src/main/java/modbus/SlaveFolder.java
>  			if (newval.getType() == ValueType.STRING && oldval.getType() == ValueType.STRING) {
use camelcase

2016-12-24 14:32 UTC, Pacane commented on src/main/java/modbus/SlaveNodeWithConnection.java
> +		double defint = node.getAttribute("polling interval").getNumber().doubleValue() / 1000;
are you sure the polling interval should be a double? I don't know what you're using, but you may consider using an int and use milliseconds.

2016-12-24 14:32 UTC, Pacane commented on src/main/java/modbus/SlaveNodeWithConnection.java
> +			int retries = event.getParameter("retries", ValueType.NUMBER).getNumber().intValue();
should be extracted and used above too.

2016-12-30 15:27 UTC, Pacane requested changes

2016-12-30 15:27 UTC, Pacane commented on src/main/java/modbus/LocalSlaveFolder.java
> +			} else if (child.getAction() == null && !(child.getName().equals("Status"))) {
Invert string comparison

2016-12-30 15:27 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +	ModbusFactory modbusFactory;
Shouldn't this be private (and final?)?

2016-12-30 15:27 UTC, Pacane commented on src/main/java/modbus/SlaveFolder.java
> +				if (restoreType.getString().equals(ATTR_RESTORE_FOLDER)) {
invert string comparison

2016-12-30 15:27 UTC, Pacane commented on src/main/java/modbus/SlaveFolder.java
> +				} else if (restoreType.getString().equals(ATTR_RESTORE_POINT)) {
Invert string comparison.

2016-12-30 15:27 UTC, Pacane commented on src/main/java/modbus/SlaveFolder.java
> +			} else if (child.getAction() == null && !(root == this && child.getName().equals("Status"))) {
Invert string comparison.

2016-12-30 15:27 UTC, Pacane commented on src/main/java/modbus/SlaveNode.java
> +        if (null != master && master.isInitialized()){
formatting

2016-12-30 15:27 UTC, Pacane commented on src/main/java/modbus/SlaveNode.java
> +		statnode = node.createChild("Status").setValueType(ValueType.STRING)
Value can be extracted.

2016-12-30 15:27 UTC, Pacane commented on src/main/java/modbus/SlaveNode.java
> +			interval = (long) (event.getParameter(ModbusConnection.ATTR_POLLING_INTERVAL, ValueType.NUMBER).getNumber()
intervalInMs

2016-12-30 15:27 UTC, Pacane commented on src/main/java/modbus/SlaveNodeWithConnection.java
> +		int defint = node.getAttribute(ModbusConnection.ATTR_POLLING_INTERVAL).getNumber().intValue() / 1000;
`defint` doesn't mean much IMO.

2016-12-30 15:27 UTC, Pacane commented on src/main/java/modbus/SlaveNodeWithConnection.java
> +			interval = (long) (event.getParameter(ModbusConnection.ATTR_POLLING_INTERVAL, ValueType.NUMBER).getNumber()
intervalInMs

2017-01-04 20:01 UTC, Pacane approved these changes

2017-01-04 20:17 UTC, merged