Feature/feature slave set
IOT-DSA/dslink-java-modbus pull request #19
Opened 2017-02-01 20:19 UTC by hhou2011

@Pacane  @d-shapiro

2017-02-01 20:22 UTC, Pacane requested changes

2017-02-01 20:22 UTC, Pacane commented on src/main/java/modbus/ModbusConnection.java
> +				connected = connected || slave.statnode.getValue().getString().equals(SlaveNode.NODE_STATUS_READY);
invert string comparison

2017-02-01 20:22 UTC, Pacane commented on src/main/java/modbus/SlaveFolder.java
> +		if (!NODE_STATUS_READY.equals(root.getStatusNode().getValue().getString()) && !checkConnectionByDevice()) {
I'd rename `checkConnectionByDevice()` for `isDeviceConnected` or something more "query"-y

2017-02-01 20:22 UTC, Pacane commented on src/main/java/modbus/SlaveFolder.java
> +		return true;
that looks wrong.

2017-02-01 20:44 UTC, d-shapiro commented on src/main/java/modbus/SlaveFolder.java
> +		return true;
yeah, could change it to ```return root.checkConnectionByDevice()```. Otherwise won't work properly when called from a subfolder.

2017-02-02 00:03 UTC, Pacane approved these changes

2017-02-02 00:08 UTC, d-shapiro approved these changes

2017-02-02 00:25 UTC, merged